### ISSUE TITLE
Build fails due to EIGEN issue

### ISSUE THREAD

**Issue by michK** [ddmarshall/Code-Eli#57]
Good day,

When I do:

```
git clone https://github.com/ddmarshall/Code-Eli.git
cd Code-Eli
cmake .
make
```

I get a bunch of errors related to EIGEN. The first error is:

```
[  1%] Building CXX object example/airfoil_fit/CMakeFiles/AirfoilFitExample.dir/airfoil_fit.cpp.o
In file included from /home/user/Code-Eli/include/eli/code_eli.hpp:32:0,
                 from /home/user/Code-Eli/include/eli/constants/math.hpp:18,
                 from /home/user/Code-Eli/example/airfoil_fit/airfoil_fit.cpp:20:
/usr/include/eigen3/Eigen/src/Core/util/Macros.h:549:26: error: ‘EIGEN_DEVICE_FUNC’
    does not name a type
```
I suspect this might mean that my environmental variables for Eigen are not set correctly. Could someone please advise me as to how to set this up, or perhaps give some advice if this is not the issue.

Thanks!

**Comment by Murmele** [comment]
I have the same issue

**Comment by acxz** [comment]
I also have the same issue.

It seems like this repo is not maintained. Here is the current maintained repo on code-eli by ramcdona.
https://github.com/ramcdona/code-eli

**Comment by michK** [comment]
Thanks for the info @acxz
